### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by dumaresq** [anonfunc/transmissio#1]
It took me a long time to get this far...
mage build did not pull down the dependencies, I had to do "go get" to do that.  Even that fails:
$ go get
transmissio.go:9:2: use of internal package not allowed
transmissio.go:10:2: use of internal package not allowed
transmissio.go:7:2: use of internal package not allowed
transmissio.go:13:2: use of internal package not allowed
I wasn't sure if that important so I went on:
$ mage build
internal/pkg/transmission/handler.go:306: G107: Potential HTTP request made with variable url (gosec)
                resp, err := http.Get(torrentLink)
Error: running "golangci-lint run --enable-all -D gochecknoglobals,gocyclo" failed with exit code 1

Any suggestions?

**Comment by anonfunc** [comment]
Re: the internal package issues, this needs to be checked out outside of the GOPATH (or modules need to be forced on).   Go must be 1.11 or newer.

The linting issue I don't get with golangci-lint version 1.13.2, but the checks might have changed.   You can build directly with `go build -o transmissio .`

**Comment by dumaresq** [comment]
Okay so moving it out of the gopath and upgrading go to 1.12.1 seems to have solved some of the issue, I can now do mage build without needing to run go get   I still get:
internal/pkg/transmission/handler.go:306: G107: Potential HTTP request made with variable url (gosec)
                resp, err := http.Get(torrentLink)
Error: running "golangci-lint run --enable-all -D gochecknoglobals,gocyclo" failed with exit code 1

The version of "golangci-lint" I have is golangci-lint has version 1.15.0 built from 901cf25 on 2019-02-18T08:24:43Z

I was able to build it directly with  go build -o transmissio .  though....
