### ISSUE TITLE
Seems to ignore downloadto directory

### ISSUE THREAD

**Issue by dumaresq** [anonfunc/transmissio#2]
I have:
blackhole: /export/nas/Downloads/Torrents/
downloadto: /export/nas/Downloads/
host: "0.0.0.0"
oauth_token: <MyToken>
port: "9091"

But when I try to download this happens:
2019/03/29 18:18:32 Sleeping 21 seconds for <file> ...
2019/03/29 18:18:53 Starting download of <file> to /export/nas/Downloads/Torrents
2019/03/29 18:26:54 Done with download of <file>
2019/03/29 18:26:54 Sleeping 10 minutes before removing transfer <file> ...
2019/03/29 18:36:54 Success: <file> to /export/nas/Downloads/Torrents

Unless I miss understood the settings I would expect it to end with the file in /export/nas/Downloads/

**Comment by anonfunc** [comment]
Looks like internal/pkg/blackhole/blackhole.go#L66 doesn't like the trailing slashes.
